# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=60, verbose_name='电影名字')),
                ('t_info', models.CharField(max_length=60, verbose_name='电影分类')),
                ('t_createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='创建时间')),
                ('t_flag', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='控制字段')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'db_table': 'tag',
                'ordering': ['-t_createtime'],
            },
        ),
    ]
