# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:08
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='art',
        ),
        migrations.AlterField(
            model_name='art',
            name='a_content',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='文章内容'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
