# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('isActive', models.BooleanField(default=False, verbose_name='用户是否被激活')),
                ('createtime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='添加时间')),
                ('flag', models.IntegerField(choices=[(0, '普通会员'), (1, 'VIP会员'), (2, '黄金会员')], default=0, verbose_name='会员控制字段')),
            ],
            options={
                'verbose_name': '会员信息',
                'verbose_name_plural': '会员信息',
                'db_table': 'arts_user',
                'ordering': ['-createtime'],
            },
        ),
    ]
