# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artsuser',
            name='isActive',
            field=models.BooleanField(default=0, verbose_name='激活'),
        ),
    ]
