# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_center', '0002_auto_20181005_0908'),
        ('books', '0005_auto_20181005_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='单价')),
                ('quantity', models.IntegerField(default=0, verbose_name='购买数量')),
                ('createtime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('flag', models.IntegerField(choices=[(0, '待下单'), (1, '已下单')], default=0, verbose_name='购买状态')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Art', verbose_name='小说商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_center.ArtsUser', verbose_name='购买用户')),
            ],
            options={
                'verbose_name': '购物车条目',
                'verbose_name_plural': '购物车条目',
                'db_table': 'line_item',
            },
        ),
        migrations.CreateModel(
            name='OrderItemRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('line_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.LineItem', verbose_name='关联条目')),
            ],
            options={
                'verbose_name': '商品条目和订单关联表',
                'verbose_name_plural': '商品条目和订单关联表',
                'db_table': 'order_item_relation',
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(unique=True, verbose_name='订单号')),
                ('pay_type', models.IntegerField(choices=[(0, '货到付款'), (1, '微信支付'), (2, '支付宝支付')], default=0, verbose_name='支付类型')),
                ('address', models.CharField(default='', max_length=200, verbose_name='订单配送地址')),
                ('phone', models.BigIntegerField(default=0, verbose_name='联系方式')),
                ('order_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下单时间')),
            ],
        ),
        migrations.AddField(
            model_name='orderitemrelation',
            name='product_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.ProductOrder', verbose_name='关联订单'),
        ),
    ]
